force-app/main/default/layouts/Contact-Contact Layout.layout-meta.xml

Fixes this error on deployment to a developer org:
=== Deploy Errors
PROJECT PATH                                                           ERRORS                                                                
─────────────────────────────────────────────────────────────────────  ──────────────────────────────────────────────────────────────────────
force-app/main/default/layouts/Contact-Contact Layout.layout-meta.xml  In field: QuickAction - no QuickAction named FeedItem.RypplePost found

remove quickActionListItem FeedItem.RypplePost

---

.prettierignore
force-app/main/default/lwc/compositionContactSearch/__tests__/compositionContactSearch.test.js
force-app/main/default/lwc/contactListItem/__tests__/contactListItem.test.js
force-app/main/default/lwc/contactListItemBubbling/__tests__/contactListItemBubbling.test.js
package-lock.json
package.json

- Ignoring coverage folder for Prettier
- Added some tests to align on lwc-recipes-oss

Test alignment with lwc-recipes-oss

---

force-app/test/jest-mocks/lightning/navigation.js
force-app/test/jest-mocks/lightning/platformShowToastEvent.js

Not the most exciting update but I've updated the URLs to fix the broken links 😄

Documentation updated to point to the correct URL

---

.circleci/config.yml
README.md

Fix syntax errors in README.md

---

force-app/main/default/lwc/apexWireMethodWithComplexParams/__tests__/apexWireMethodWithComplexParams.test.js
force-app/main/default/lwc/apexWireMethodWithComplexParams/apexWireMethodWithComplexParams.js

Fix complex Apex parameter recipe

---

force-app/main/default/lwc/contactList/contactList.js

The PR fixes the typo in the class name. Fixes #248  issue.

fix for issue -248. Add relevant class name

---

force-app/main/default/aura/lmsPublisherAuraComponent/lmsPublisherAuraComponent.cmp
force-app/main/default/aura/lmsPublisherAuraComponent/lmsPublisherAuraComponent.css
force-app/main/default/aura/lmsPublisherAuraComponent/lmsPublisherAuraComponentController.js
force-app/main/default/aura/lmsSubscriberAuraComponent/lmsSubscriberAuraComponent.cmp
force-app/main/default/aura/lmsSubscriberAuraComponent/lmsSubscriberAuraComponent.css
force-app/main/default/aura/lmsSubscriberAuraComponent/lmsSubscriberAuraComponentController.js

Updates to 
lmsPublisherAuraComponent
lmsSubscriberAuraComponent
Applied contact list-contact detail use case and updated to reflect UX of other similar recipes including aura pill identifier on the lightning-card.

Merge LMS example into beta branch

---

force-app/main/default/lwc/lmsPublisherWebComponent/lmsPublisherWebComponent.css
force-app/main/default/lwc/lmsPublisherWebComponent/lmsPublisherWebComponent.html
force-app/main/default/lwc/lmsPublisherWebComponent/lmsPublisherWebComponent.js
force-app/main/default/lwc/lmsSubscriberWebComponent/lmsSubscriberWebComponent.css
force-app/main/default/lwc/lmsSubscriberWebComponent/lmsSubscriberWebComponent.html
force-app/main/default/lwc/lmsSubscriberWebComponent/lmsSubscriberWebComponent.js

Moves the LWC example to the Contact List-Contact Detail flow for the final use case.

Update LWC with Final LMS Use Case

---

force-app/main/default/lwc/compositionBasics/compositionBasics.css
force-app/main/default/lwc/compositionIteration/compositionIteration.css
force-app/main/default/lwc/cssLibrary/cssLibrary.css
force-app/main/default/lwc/cssLibrary/cssLibrary.js-meta.xml

Refactor common CSS from `compositionIteration` and `compositionBasics` components into a `cssLibrary` module.
#291 
NA
Look and feel should remain the same.

sharing css styles among Lightning web components

---

force-app/main/default/applications/LWC_Recipes.app-meta.xml

Rename app to "LWC Recipes"
https://github.com/trailheadapps/lwc-recipes/issues/299
[ x] Tests for the proposed changes have been added/updated.
[ x] Code linting and formatting was performed.

Rename app to "LWC Recipes"

---

.github/workflows/scratch-org-sfdx-ci-master.yml
.github/workflows/scratch-org-sfdx-ci-pr-prerelease.yml
.github/workflows/scratch-org-sfdx-ci-pr.yml

Updated codecov.io actions in CI workflows.

Codecov update

---

.eslintignore
.github/workflows/branch-naming.yml
.github/workflows/scratch-org-sfdx-ci-master.yml
.github/workflows/scratch-org-sfdx-ci-pr-prerelease.yml
.github/workflows/scratch-org-sfdx-ci-pr.yml
force-app/main/default/aura/.eslintrc.json
force-app/main/default/aura/auraEmbeddedLWC/auraEmbeddedLWCController.js
force-app/main/default/aura/auraPubsubPublisher/auraPubsubPublisherController.js
force-app/main/default/aura/auraPubsubSubscriber/auraPubsubSubscriberController.js
force-app/main/default/lwc/.eslintrc.json
package-lock.json
package.json

- Used ESLint to lint Aura instead of CLI (deprecated)
- Fixed new linting error reported after linter update

Moved Aura linting to ESLint

---

force-app/main/default/classes/TestLMSVisualforceController.cls
force-app/main/default/classes/TestLMSVisualforceController.cls-meta.xml

Adds unit test for Apex controller used in LMS recipes. 
One more item ticked off for #253. 
New apex class required for the recipe must have 
[X] Tests for the proposed changes have been added/updated.
No tests for LMSVisualforceController.cls
Working and passing tests for LMSVisualforceController.cls with 100% code coverage no new lines of code.

Added apex unit tests for LMSVisualforceController

---

force-app/main/default/aura/lmsPublisherAuraComponent/lmsPublisherAuraComponent.cmp
force-app/main/default/aura/lmsSubscriberAuraComponent/lmsSubscriberAuraComponent.cmp
force-app/main/default/flexipages/Message_Service.flexipage-meta.xml
force-app/main/default/lwc/ldsGenerateRecordInputForCreate/ldsGenerateRecordInputForCreate.html
force-app/main/default/lwc/lmsPublisherWebComponent/lmsPublisherWebComponent.html
force-app/main/default/lwc/lmsSubscriberWebComponent/lmsSubscriberWebComponent.html

Several recipe labels from recently added recipes were out of sync with the rest of the recipes. Corrected them so that all are now upper camel case. 
~[ ] Tests for the proposed changes have been added/updated.~

✏️  bring recipe label format into sync

---

README.md

Added Trailhead CTA with badge icon.

Added Trailhead CTA

---

README.md

Added permission set assignment instructions for package installation.

Added perm set instructions for package install

---

package-lock.json
package.json

Upgrade sa11y version
The app was using sa11y/jest 0.1.3
The app is using sa11y/jest 0.1.4

Upgrade sa11y version

---

package-lock.json
package.json

updates to latest husky version after dependabot PR became too stale

husky update

---

LICENSE.md

The Github UI does not pick the license if the legal code is missing in the header.

fix: Update License with legal code

---

.github/workflows/scratch-org-sfdx-ci-pr.yml
force-app/main/default/pages/lmsSubscriberVisualforcePostbackAction.page

Adds automation to run security scans using Salesforce CLI Scanner (uses PMD internally) on pull request.

feat: add PMD security scans using Salesforce CLI scanner plugin

---

force-app/main/default/lwc/apiSetterGetter/apiSetterGetter.css
force-app/main/default/lwc/apiSetterGetter/apiSetterGetter.html

Fixes UI bug for apiGetterSetter component.
#408 
[X] Tests for the proposed changes have been added/updated.
Clicking on white space to right of visible button invoked event handler because `lightningButton` was set to `display:block`. 
Event handler on invoked when clicking on button.

fixed html structure and css

---

.github/workflows/scratch-org-sfdx-ci-pr.yml

fix: remove echo as sfdx scanner plugin is digitally signed

---

README.md

Takes out my domain instructions from README.md as new DE orgs now auto-enable my domain. 
Also, removed reference to "30 lines of code" from README.md.
#427

removed my domain step

---

force-app/main/default/lwc/pubsub/README.md

Added a note about pub/sub limitations (no Community support).

Added a note about pub/sub limitations

---

force-app/main/default/lwc/ldsUtils/__tests__/ldsUtils.test.js
force-app/main/default/lwc/ldsUtils/ldsUtils.js

Improve Apex Error Handling in LDS Utils
#445

Improved ldsUtils to handle apex errors

---

package-lock.json
package.json

Updated Aura @salesforce/eslint-plugin-aura to v2.0.0

Updated Aura linter

---

force-app/main/default/lwc/navToNewRecordWithDefaults/__tests__/navToNewRecordWithDefaults.test.js
force-app/main/default/lwc/navToNewRecordWithDefaults/navToNewRecordWithDefaults.js

Test was disabled pending for a sfdx-lwc-jest bug fix. I've uncommented the test and made sure that it works.

bug: Fixed NavToNewRecordWithDefaults test

---

force-app/main/default/lwc/apexStaticSchema/__tests__/apexStaticSchema.test.js
force-app/main/default/lwc/apexWireMethodToFunction/__tests__/apexWireMethodToFunction.test.js
force-app/main/default/lwc/apexWireMethodToProperty/__tests__/apexWireMethodToProperty.test.js
force-app/main/default/lwc/apexWireMethodWithComplexParams/__tests__/apexWireMethodWithComplexParams.test.js
force-app/main/default/lwc/apexWireMethodWithParams/__tests__/apexWireMethodWithParams.accessibility.test.js
force-app/main/default/lwc/apexWireMethodWithParams/__tests__/apexWireMethodWithParams.test.js
force-app/main/default/lwc/contactList/__tests__/contactList.test.js
force-app/main/default/lwc/eventBubbling/__tests__/eventBubbling.test.js
force-app/main/default/lwc/eventWithData/__tests__/eventWithData.test.js
force-app/main/default/lwc/lds/__tests__/lds.test.js
force-app/main/default/lwc/ldsDeleteRecord/__tests__/ldsDeleteRecord.test.js
force-app/main/default/lwc/ldsGenerateRecordInputForCreate/__tests__/ldsGenerateRecordInputForCreate.test.js
force-app/main/default/lwc/lmsPublisherWebComponent/__tests__/lmsPublisherWebComponent.test.js
force-app/main/default/lwc/lmsSubscriberWebComponent/__tests__/lmsSubscriberWebComponent.test.js
force-app/main/default/lwc/navToRecord/__tests__/navToRecord.test.js
force-app/main/default/lwc/navToRelatedList/__tests__/navToRelatedList.test.js
force-app/main/default/lwc/wireCurrentPageReference/__tests__/wireCurrentPageReference.test.js
force-app/main/default/lwc/wireGetObjectInfo/__tests__/wireGetObjectInfo.test.js
force-app/main/default/lwc/wireGetPicklistValues/__tests__/wireGetPicklistValues.test.js
force-app/main/default/lwc/wireGetPicklistValuesByRecordType/__tests__/wireGetPicklistValuesByRecordType.test.js
force-app/main/default/lwc/wireGetRecordDynamicContact/__tests__/wireGetRecordDynamicContact.test.js
force-app/main/default/lwc/wireGetRecordStaticContact/__tests__/wireGetRecordStaticContact.test.js
force-app/main/default/lwc/wireGetRecordUser/__tests__/wireGetRecordUser.test.js
force-app/main/default/lwc/wireListView/__tests__/wireListView.test.js
force-app/test/jest-mocks/lightning/navigation.js
force-app/test/jest-mocks/lightning/uiRecordApi.js
package-lock.json
package.json

Update tests following reform to the wire protocol
Fixes the issue #517

Updated tests following reform to the wire protocol

---

force-app/main/default/lwc/editRecordScreenAction/__tests__/editRecordScreenAction.test.js
force-app/main/default/lwc/miscGetUserId/__tests__/miscGetUserId.test.js
package-lock.json
package.json

Bump Node package versions 
This PR bumps node package versions in PRs #526, #527, #536, #537, #538, #542 
NA
[ X] Tests for the proposed changes have been added/updated.
[ X] Code linting and formatting were performed.

Bumped Node package versions

---

force-app/main/default/lwc/editRecordScreenAction/__tests__/data/getRecord.json
force-app/main/default/lwc/editRecordScreenAction/__tests__/editRecordScreenAction.test.js
force-app/main/default/lwc/editRecordScreenAction/editRecordScreenAction.html
force-app/main/default/lwc/editRecordScreenAction/editRecordScreenAction.js

Fixes the update issue in the Edit Record Quick Action
Edit Record Button is throwing error on update
NA

fix: Edit Record Action button updates the contact

---

.husky/pre-commit
force-app/main/default/lwc/ldsUtils/__tests__/ldsUtils.test.js
force-app/main/default/lwc/ldsUtils/ldsUtils.js

Updated the reduce errors function to handle validation rule errors 
#557

Added error handling for validation rules

---

.forceignore

Fixes the deployment issue to the Trailhead Playground 
Deploying to Trailhead playground failed
closes issue [#587](https://github.com/trailheadapps/lwc-recipes/issues/587)
Deployment to the Trailhead Playground fails with the message 
`An object 'pubsub' of type LightningComponentBundle was named in package.xml, but was not found in zipped directory`
Successfully deploys to the Trailhead Playground

FIX: Failing deployment in playground

---

force-app/main/default/lwc/compositionContactSearch/__tests__/compositionContactSearch.test.js
force-app/main/default/lwc/errorPanel/templates/noDataIllustration.html
force-app/main/default/lwc/eventSimple/eventSimple.html
force-app/main/default/lwc/libsD3/__tests__/libsD3.test.js
force-app/main/default/lwc/modal/modal.html
package-lock.json

- simplified CSS selector in LibsD3 test
- removed duplicate calls to jest.useFakeTimers() in compositionContactSearch test

Minor fixes

---

force-app/main/default/lwc/errorPanel/templates/noDataIllustration.html
force-app/main/default/lwc/eventSimple/eventSimple.html
force-app/main/default/lwc/modal/modal.html
package-lock.json
package.json

Bump Node Package Versions
NA
[ X ] Code linting and formatting was performed.

Bump Node Package Versions

---

force-app/main/default/lwc/customDataTypes/customPicture.css
force-app/main/default/lwc/customDataTypes/customPicture.html
force-app/main/default/lwc/datatableInlineEditWithUiApi/datatableInlineEditWithUiApi.js

Refactoring and optimizing the code

code optimization

---

force-app/main/default/lwc/libsFullCalendar/libsFullCalendar.html

Updated the url from lwc/libsD3 to lwc/libsFullCalender

View source navigation fix

---

force-app/main/default/flexipages/Misc_Techniques.flexipage-meta.xml
force-app/main/default/lwc/miscStylingHooks/miscStylingHooks.css
force-app/main/default/lwc/miscStylingHooks/miscStylingHooks.html
force-app/main/default/lwc/miscStylingHooks/miscStylingHooks.js
force-app/main/default/lwc/miscStylingHooks/miscStylingHooks.js-meta.xml
force-app/main/default/lwc/viewSource/viewSource.css
sfdx-project.json

feat: added styling hooks recipe

---

force-app/main/default/lwc/datatableInlineEditWithApex/datatableInlineEditWithApex.js
force-app/main/default/lwc/datatableInlineEditWithUiApi/datatableInlineEditWithUiApi.js

Made some minor improvements to the datatable recipes in preparation for including them in documentation:
- improved code alignment between the two JS files
- added a note about using Apex to fetch records in `datatableInlineEditWithUiApi` while waiting for a replacement to `getListUi()`

Minor improvements to the datatable recipes

---

force-app/main/default/classes/CustomWrapper.cls
force-app/main/default/classes/TestApexTypeController.cls
force-app/main/default/lwc/apexImperativeMethodWithComplexParams/__tests__/apexImperativeMethodWithComplexParams.test.js
force-app/main/default/lwc/apexImperativeMethodWithComplexParams/apexImperativeMethodWithComplexParams.js
force-app/main/default/lwc/apexWireMethodWithComplexParams/__tests__/apexWireMethodWithComplexParams.test.js
force-app/main/default/lwc/apexWireMethodWithComplexParams/apexWireMethodWithComplexParams.js
package-lock.json
package.json

We removed the inner class from the wrapper used in Apex complex param type as it it's not supported.

fix: removed inner class from Apex complex param type

---

force-app/main/default/lwc/modal/modal.js

[x ] Tests for the proposed changes have been added/updated.
[ x] Code linting and formatting was performed.
Modal code is simpler.

Modal refactoring

---

force-app/main/default/lwc/miscRestApiCall/miscRestApiCall.html
force-app/main/default/lwc/miscRestApiCall/miscRestApiCall.js
package-lock.json
package.json

Adds a spinner while the fetch call is being run. Updated the recipe to use async/await.

feat: added spinner for REST API recipe

---

force-app/main/default/classes/ContactController.cls
force-app/main/default/classes/TestContactController.cls
force-app/main/default/flexipages/Contact_Record_Page.flexipage-meta.xml
force-app/main/default/lwc/ldsNotifyRecordUpdateAvailable/__tests__/data/getRecord.json
force-app/main/default/lwc/ldsNotifyRecordUpdateAvailable/__tests__/ldsNotifyRecordUpdateAvailable.test.js
force-app/main/default/lwc/ldsNotifyRecordUpdateAvailable/ldsNotifyRecordUpdateAvailable.html
force-app/main/default/lwc/ldsNotifyRecordUpdateAvailable/ldsNotifyRecordUpdateAvailable.js
force-app/main/default/lwc/ldsNotifyRecordUpdateAvailable/ldsNotifyRecordUpdateAvailable.js-meta.xml
force-app/test/jest-mocks/lightning/uiRecordApi.js

Creates a new recipe to show the usage of uiRecordApi/notifyRecordUpdateAvailable

Added new recipe for notifyRecordUpdateAvailable

---

force-app/main/default/permissionsets/recipes.permissionset-meta.xml

Adds the missing permission to view Refresh View Tab

Added permission for the Refresh View Tab

---

package-lock.json
package.json

Resolve the package version updates to the latest versions

Resolving package conflicts

---

force-app/main/default/lwc/apexImperativeMethodWithComplexParams/apexImperativeMethodWithComplexParams.html
force-app/main/default/lwc/apexImperativeMethodWithParams/apexImperativeMethodWithParams.html
force-app/main/default/lwc/apexWireMethodWithComplexParams/apexWireMethodWithComplexParams.html
force-app/main/default/lwc/compositionContactSearch/compositionContactSearch.html
force-app/main/default/lwc/wireGetObjectInfo/wireGetObjectInfo.html
force-app/main/default/lwc/wireGetRecord/wireGetRecord.html
force-app/main/default/lwc/wireGetRecords/wireGetRecords.html
force-app/main/default/lwc/wireGetRecordsDifferentTypes/wireGetRecordsDifferentTypes.html
package-lock.json

Makes elseif usage for errors consistent

Making elseif usage for errors consistent

---

force-app/main/default/classes/TestAccountController.cls
force-app/main/default/classes/TestApexTypeController.cls
force-app/main/default/classes/TestContactController.cls
force-app/main/default/classes/TestLMSVisualforceController.cls
force-app/main/default/lwc/dispatchRefreshEvent/dispatchRefreshEvent.js
force-app/main/default/lwc/ldsNotifyRecordUpdateAvailable/ldsNotifyRecordUpdateAvailable.js

Use Assert Class for assertions and fix other reviewed changes

Use Assert Class for assertions and fix other reviewed changes

---

data/Accounts.json
force-app/main/default/classes/AccountController.cls
force-app/main/default/classes/ContactController.cls
force-app/main/default/classes/LMSVisualforceController.cls
force-app/main/default/classes/TestAccountController.cls
force-app/main/default/flexipages/GraphQL.flexipage-meta.xml
force-app/main/default/lwc/graphqlRefresh/__tests__/data/graphqlAccountResponse.json
force-app/main/default/lwc/graphqlRefresh/__tests__/data/graphqlNoAccountResponse.json
force-app/main/default/lwc/graphqlRefresh/__tests__/graphqlRefresh.test.js
force-app/main/default/lwc/graphqlRefresh/graphqlRefresh.html
force-app/main/default/lwc/graphqlRefresh/graphqlRefresh.js
force-app/main/default/lwc/graphqlRefresh/graphqlRefresh.js-meta.xml

Added a recipe that demonstrates graphqlRefresh

feat: graphqlRefresh recipe

---

force-app/main/default/flexipages/GraphQL.flexipage-meta.xml
force-app/main/default/lwc/graphqlContacts/graphqlContacts.html
force-app/main/default/lwc/graphqlContacts/graphqlContacts.js
force-app/main/default/lwc/graphqlMultipleObjects/__tests__/data/graphqlMultipleObjectsResponse.json
force-app/main/default/lwc/graphqlMultipleObjects/__tests__/graphqlMultipleObjects.test.js
force-app/main/default/lwc/graphqlMultipleObjects/graphqlMultipleObjects.html
force-app/main/default/lwc/graphqlMultipleObjects/graphqlMultipleObjects.js
force-app/main/default/lwc/graphqlMultipleObjects/graphqlMultipleObjects.js-meta.xml
force-app/main/default/lwc/graphqlPagination/graphqlPagination.html
force-app/main/default/lwc/graphqlRefresh/graphqlRefresh.html
force-app/main/default/lwc/graphqlRefresh/graphqlRefresh.js
force-app/main/default/lwc/graphqlVariables/graphqlVariables.html
package-lock.json

Add multi object query graphql recipe
Fix small issues
[X] Tests for the proposed changes have been added/updated.

Multi object query graphql recipe

---

force-app/main/default/lwc/contactInfo/__tests__/contactInfo.test.js
force-app/main/default/lwc/contactInfo/__tests__/data/getRecord.json
force-app/main/default/lwc/lmsSubscriberWebComponent/__tests__/data/getRecord.json
force-app/main/default/lwc/lmsSubscriberWebComponent/__tests__/data/getRecordNoPicture.json
force-app/main/default/lwc/lmsSubscriberWebComponent/__tests__/lmsSubscriberWebComponent.test.js
force-app/main/default/lwc/wireGetRecordStaticContact/__tests__/data/getRecord.json
force-app/main/default/lwc/wireGetRecordStaticContact/__tests__/wireGetRecordStaticContact.test.js
force-app/test/jest-mocks/lightning/uiRecordApi.js
package-lock.json
package.json

Uses uiRecordApi's latest mock implementation from https://github.com/salesforce/sfdx-lwc-jest/blob/master/src/lightning-stubs/uiRecordApi/uiRecordApi.js. 
#866

Updated jest mock for uiRecordApi

---

force-app/main/default/lwc/myModal/__tests__/myModal.test.js
force-app/main/default/lwc/myModal/myModal.html
jest.config.js

Adds test cases for the modal component 
#736 
[ X ] Code linting and formatting was performed.

feat: added test cases for the modal component
