trailheadapps/lwc-recipes

force-app/main/default/classes/ContactController.cls

If an empty string is passed down as a parameter this Apex call returns the full list of all Contact records. For example is when the user enters data in `contactCompositionSearch`, and then clears the data.
This fix checks the searchKey parameter and returns an empty list in case an empty string is the parameter.

Fix Apex return statement

---

force-app/main/default/lwc/pubsub/pubsub.js

An internal code review of code that used this raised the issue that this method had no header comment. Added here to help others in similar boats.

Add method header to `samePageRef`

---

force-app/main/default/cspTrustedSites/googleapis.cspTrustedSite-meta.xml

To follow principle of least access, adding the `connect-src` CSP rule to the googleapis CSP rules. 
This replaces PR #302 to make the merge into `prerelease/summer20` easier.

added connect-src allow rule

---

force-app/main/default/applications/LWC_Recipes.app-meta.xml

Resolves issue #158. Reorders app tabs to show **Data Service** first and then **Apex**.

moves data service tab before apex tab

---

force-app/main/default/customPermissions/accessRestrictedUIPermission.customPermission-meta.xml
force-app/main/default/lwc/miscPermissionBasedUI/miscPermissionBasedUI.html
force-app/main/default/lwc/miscPermissionBasedUI/miscPermissionBasedUI.js
force-app/main/default/lwc/miscPermissionBasedUI/miscPermissionBasedUI.js-meta.xml
force-app/main/default/permissionsets/Access_Restricted_UI.permissionset-meta.xml

Includes addition of one new recipe to show interaction of LWC with custom permission. Includes:
- Custom permission
- Permission set with the custom permission
- Component that imports the permission and conditionally renders part of the UI 
Caveat: the permission set must be manually assigned (or unassigned) and the page refreshed to view the change. This is stipulated in the recipe comments in the UI.

Added features for permission-based recipe

---

force-app/main/default/lwc/miscMultipleTemplates/__tests__/miscMultipleTemplates.test.js

Adds test suite for c/miscMultipleTemplates

added test suite for c/miscMultipleTemplates

---

force-app/main/default/flexipages/Misc_Techniques.flexipage-meta.xml

NOT FOR JEST BLITZ
The new custom permission-based component inclusion in the flexipage was missed in the original PR #322. This PR adds the flexipage so it will appear on the UI.

Adding flexipage for permissions recipe

---

.forceignore

Found an issue with .forceignore and the pubsub readme that this fixes.

fixed forceignore for README

---

force-app/main/default/lwc/miscPermissionBasedUI/__tests__/miscPermissionBasedUI.test.js
force-app/main/default/lwc/miscPermissionBasedUI/miscPermissionBasedUI.html

This adds a basic test to the miscPermissionsBasedUI component. We can expand on it later. 
#340

basic working test

---

force-app/main/default/layouts/Account-Account Layout.layout-meta.xml

addresses issue #376 to remove EOL Rypple quick action from account layout.

removed old work.com quick action

---

force-app/main/default/permissionsets/recipes.permissionset-meta.xml

Addresses apex execution permission requirements added in the Winter 21 critical [release](https://releasenotes.docs.salesforce.com/en-us/summer20/release-notes/rn_lc_restrict_apex_authenticated_users.htm) requiring executing user to have execution access to any apex classes via either profile or permission set. This PR adds those permissions to the `recipes` permission set. 

added apex class access to permset

---

README.md
config/project-scratch-def.json
force-app/main/default/lightningOnboardingConfigs/LightningOnboardingConfig.lightningOnboardingConfig-meta.xml
force-app/main/default/prompts/CompositionWalkthrough.prompt-meta.xml
force-app/main/default/prompts/DataWalkthrough.prompt-meta.xml
force-app/main/default/prompts/HelloWalkThrough.prompt-meta.xml
force-app/main/default/prompts/Miscand3rdPartyWalkthrough.prompt-meta.xml

Adds 3 in-app guidance walkthroughs to the sample app
No Walkthroughs
4 Walkthroughs
- Hello: welcome to the sample app. What to look for, how to find code, and interact with the hello page
- Data: Covers LDS, Apex, and Wire
- Composition: Covers composition, child-to-parent, parent-to-child, navigation, aura interop, and LMS
- 3rd Part and Misc: Covers those two tabs

Add 4 In App Guidance walkthroughs

---

.gitignore
.vscode/extensions.json
README.md

Added CodeTour as a recommended VS Code extension. This brings up a prompt that suggest installing the extension when the user imports the project.
If users don't have the extension, our tours are pretty useless :)

Added CodeTour as a recommended VS Code extension

---

config/project-scratch-def.json

Move EnableSetPasswordInApi to `features` in the `project-scratch-def.json` file to conform to this being deprecated from `settings` in api v51.0.

moved EnableSetPasswordInApi to features

---

force-app/test/jest-mocks/lightning/uiRecordApi.js

Remove `getRecordUI` and `getRecordInput` wire adapters as they are being deprecated by the LDS team. Those API will be removed in 240.

chore: Remove uiRecordApi deprecated endpoints

---

force-app/main/default/lwc/datatableCustomDataType/datatableCustomDataType.html

Fix datataleCustomDataType to datatableCustomDataType
Corrects html link to github typo 
#618
[ N/A] Tests for the proposed changes have been added/updated.
[ N/A] Code linting and formatting was performed.

 datatableCustomDataType html view-source typo

---

force-app/main/default/lwc/navToChatterHome/__tests__/navToChatterHome.test.js
force-app/main/default/lwc/navToFilesHome/__tests__/navToFilesHome.test.js
force-app/main/default/lwc/navToHelloTab/__tests__/navToHelloTab.test.js
force-app/main/default/lwc/navToHome/__tests__/navToHome.test.js
force-app/main/default/lwc/navToListView/__tests__/navToListView.test.js
force-app/main/default/lwc/navToNewRecord/__tests__/navToNewRecord.test.js
force-app/main/default/lwc/navToNewRecordWithDefaults/__tests__/navToNewRecordWithDefaults.test.js
force-app/main/default/lwc/navToRelatedList/__tests__/navToRelatedList.test.js
force-app/test/jest-mocks/lightning/navigation.js

- Uses `jest.fn()` functions to receive the `lightning/navigation` mock calls so the mock can be reset.
- Updates any existing test that used the navigation helper to reset all mocks.
Note: This repository did not contain any existing failures. Please see the first commit (da77ad518aeda26a7be6856c8a13fa3a695b15ea) for a demonstration of how a user might encounter this issue. I'm proposing this fix to minimize overall test changes so that users could easily consume this mock change without a refactor of their existing tests.
A more thorough fix would be to export the `mockNavigate` and `mockGenerate` constants (with better names) and remove the `getNavigateCalledWith` and `getGenerateUrlCalledWith` helper functions but this would be a more extensive refactor and a breaking change for …

Make the lightning/navigation mock resettable

---

force-app/main/default/lwc/libsChartjs/libsChartjs.js
force-app/main/default/lwc/libsD3/libsD3.js
force-app/main/default/lwc/libsD3/libsD3.js-meta.xml
force-app/main/default/lwc/libsFullCalendar/libsFullCalendar.js
force-app/main/default/lwc/libsFullCalendar/libsFullCalendar.js-meta.xml
force-app/main/default/lwc/resourceLoader/resourceLoader.js
force-app/main/default/lwc/resourceLoader/resourceLoader.js-meta.xml

Adds a custom library to load scripts in LWR Sites. This workaround is implemented to get around a limitation of the Lightning Locker library in LWR sites. Read more about it in the "Lightning Locker Limitations" section of the [documentation](https://developer.salesforce.com/docs/atlas.en-us.exp_cloud_lwr.meta/exp_cloud_lwr/template_limitations.htm)
#744 
Components `libsD3`, `libsChartjs` and `libsFullCalendar` don't load in an LWR site
Components `libsD3`, `libsChartjs` and `libsFullCalendar` successfully load in an LWR site

Added custom library to load scripts in LWR Sites

---

force-app/main/default/lwc/contactTile/contactTile.html
force-app/main/default/lwc/graphqlContacts/graphqlContacts.js
force-app/main/default/lwc/graphqlContacts/graphqlContacts.js-meta.xml
force-app/main/default/lwc/graphqlPagination/graphqlPagination.js-meta.xml
force-app/main/default/lwc/graphqlVariables/graphqlVariables.js-meta.xml

Temporary workaround for a GraphQL bug that prevents the use of custom fields on a standard object.

fix: graphql custom field bug workaround

---

force-app/main/default/lwc/wireListView/wireListView.js

Document that the listViewApiName should be updated when copying this code to a non-recipe org.
#663 -- seems to be confused that because this is deprecated it is not working. The wire still works despite being deprecated, it is likely they hit an error due to the org not having the list view referenced. 
comment only change
No code comment which led to confusion when copying code to other orgs.
Code comment added for clarity.

docs: clarify listViewApiName needs updated if not using recipe org

---

force-app/main/default/lwc/apiSpread/__tests__/apiSpread.test.js
force-app/main/default/lwc/contactInfo/__tests__/contactInfo.test.js
force-app/main/default/lwc/contactSelector/__tests__/contactSelector.test.js
force-app/main/default/lwc/datatableCustomDataType/__tests__/datatableCustomDataType.test.js
force-app/main/default/lwc/datatableInlineEditWithApex/__tests__/datatableInlineEditWithApex.test.js
force-app/main/default/lwc/datatableInlineEditWithUiApi/__tests__/datatableInlineEditWithUiApi.test.js
force-app/main/default/lwc/dispatchRefreshEvent/__tests__/dispatchRefreshEvent.test.js
force-app/main/default/lwc/dispatchRefreshEvent/dispatchRefreshEvent.js
force-app/main/default/lwc/ldsNotifyRecordUpdateAvailable/__tests__/ldsNotifyRecordUpdateAvailable.test.js
force-app/main/default/lwc/ldsNotifyRecordUpdateAvailable/ldsNotifyRecordUpdateAvailable.js
force-app/main/default/lwc/lightDomQuery/__tests__/lightDomQuery.test.js
force-app/main/default/lwc/lightDomQueryChild/__tests__/lightDomQueryChild.test.js
force-app/main/default/lwc/navigateToRecordHeadlessAction/__tests__/navigateToRecordHeadlessAction.test.js

Normalizes all inline comments in JS files to have a space after the `//` token.
Improves readability and code consistency.
n/a
[x] ~~Tests for the proposed changes have been added/updated.~~ (_I believe it's not applicable_)
No functional changes
same

Normalize components whitespace

---

README.md

This PR addresses a typo in the README instructions and updates the name of an app for clarity and accuracy. It improves the readability and accuracy of the provided instructions for deploying an application to a more permanent environment within Salesforce.
No issue tracked. This is a proactive fix.
The original README instructions contained a typo and referred to the app as "LWC" which caused confusion for users.
The README instructions have been updated to fix the typo and provide a more accurate app name, "LWC Recipes." This change improves the user experience by ensuring clear and accurate instructions for deploying the application to a more permanent environment.

Typo Fix and App Name Update in README Instructions

---

force-app/main/default/flexipages/GraphQL.flexipage-meta.xml
force-app/main/default/tabs/GraphQL.tab-meta.xml

Remove "(Beta)" qualifier from GraphQL recipes tab since GraphQL wire adapter is GA in Winter '24 release.
[ n/a ] Tests for the proposed changes have been added/updated.
[ n/a ] Code linting and formatting was performed.
GraphQL tab label contained "(Beta)" qualifier.
"(Beta)" qualifier has been removed from GraphQL tab.

feat: remove "(Beta)" from GraphQL recipes

---

force-app/main/default/lwc/recordPickerDynamicTarget/recordPickerDynamicTarget.html
force-app/main/default/lwc/recordPickerDynamicTarget/recordPickerDynamicTarget.js
force-app/main/default/lwc/recordPickerHello/recordPickerHello.js

Chore: adding more comments to the code to give some explanation.

chore(record-picker): add some comments

---

force-app/main/default/classes/AccountController.cls
force-app/main/default/classes/TestAccountController.cls
force-app/main/default/flexipages/Refresh_View.flexipage-meta.xml
force-app/main/default/lwc/dispatchRefreshEvent/dispatchRefreshEvent.html
force-app/main/default/lwc/viewToRefresh/__tests__/data/getRecord.json
force-app/main/default/lwc/viewToRefresh/__tests__/data/getRecordNoPicture.json
force-app/main/default/lwc/viewToRefresh/__tests__/viewToRefresh.test.js
force-app/main/default/lwc/viewToRefresh/viewToRefresh.html
force-app/main/default/lwc/viewToRefresh/viewToRefresh.js
force-app/main/default/lwc/viewToRefresh/viewToRefresh.js-meta.xml
force-app/test/jest-mocks/lightning/refresh.js

Adds more examples for RefreshView API
[X] Tests for the proposed changes have been added/updated.

Expand refresh view api recipes

---

force-app/main/default/flexipages/Misc_Techniques.flexipage-meta.xml
force-app/main/default/lwc/miscLogger/__tests__/miscLogger.test.js
force-app/main/default/lwc/miscLogger/miscLogger.html
force-app/main/default/lwc/miscLogger/miscLogger.js
force-app/main/default/lwc/miscLogger/miscLogger.js-meta.xml
force-app/test/jest-mocks/lightning/logger.js
jest.config.js

Adds a recipe to showcase how to use the new logger function for event monitoring 

Add logger recipe (Esteve Graells code)

---

config/project-scratch-def.json

This PR enables Local Dev feature in scratch orgs. See [Preview Components with Local Dev](https://developer.salesforce.com/docs/platform/lwc/guide/get-started-test-components.html) for more information.
* Tests for the proposed changes have been added/updated: Not needed.
* Code linting and formatting was performed: Not needed
The user had to activate Local Dev manually in the Salesforce setup.
The user does not need to manually activate Local Dev in the Salesforce setup.

enable Local Dev
